#服务端口
server:
  port: 7778

#logback日志配置文件路径
logging:
  config: classpath:logback-spring.xml

#spring配置
spring:
  #thymeleaf配置
  thymeleaf:
    #prefix只能写成classpath:/templates/ 如果只写成 /templates/会报错
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    #测试环境下缓存关闭，正式环境打开
    cache: false
    mode: HTML
    encoding: UTF-8
    check-template-location: false

  #分环境配置
  profiles:
    active: dev

  #数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #JDBC配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.126.136:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

    #Druid 连接池配置
    druid:
      # 初始连接数 #
      initial-size: 5
      # 最大的活跃连接数 #
      max-active: 30
      # 指定必须保持连接的最小值 #
      min-idle: 3
      # 测试SQL #
      validation-query: SELECT 'x' FROM DUAL
      # 超时等待时间 #
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 #
      time-between-eviction-runs-millis: 60000
      # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒 #
      min-evictable-idle-time-millis: 300000
      # 当连接空闲时，是否执行连接测试 #
      test-while-idle: true
      # 当从连接池借用连接时，是否测试该连接 #
      test-on-borrow: false
      # 在连接归还到连接池时是否测试该连接 #
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙 #
      # 监控统计用的filter:stat   日志用的filter:slf4j   防御sql注入的filter:wall #
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        url-pattern: /*
        # 排除统计干扰 #
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        # 白名单 #
        allow: 127.0.0.1
        deny:
        enabled: true
        url-pattern: /druid/*
          # 是否能够重置数据 #
        reset-enable: true
        #druid监控页面账号密码，页面 ip:port/druid/login.html
        login-username: druid
        login-password: druid

#pagehelper配置
pagehelper:
  #使offset跟pageNum等同，limit与pageSize含义相同
  offset-as-page-num: true
  #设置在分页查询时，把总数也查出来
  row-bounds-with-count: true
  #当 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果。
  page-size-zero: true
  #pageNum<=0 会查询第一页，如果 pageNum>总页数 会查询最后一页。
  reasonable: false
  #  params: pageNum=pageNum;pageSize=pageSize;
  #-------------------------------------------
  #support-methods-arguments如果设置为true，
  #则可以直接通过参数传入pageNum和pageSize，同时要配置pageNum和pageSize，如上。
  #同时在参数面前添加@Param('pageNum') 这样的注解
  #-------------------------------------------
  support-methods-arguments: false
  helper-dialect: mysql



#Mybatis配置
mybatis:
  type-aliases-package: com.viatom.messagepushing.pojo
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml